### ISSUE TITLE
Filament Cut Lenght WorksSheet not visible

### ISSUE THREAD

**Issue by scmanjarrez** [bmoniey/pylen#1]
Hi,
I've tried adding some segments to the filament cut length worksheet window, but it doesn't show anything:
![image](https://user-images.githubusercontent.com/9284124/119226304-b7a35800-bb08-11eb-8b58-861e9e5ccf70.png)
![image](https://user-images.githubusercontent.com/9284124/119225946-fe904e00-bb06-11eb-8203-9a0800e8a29c.png)
![image](https://user-images.githubusercontent.com/9284124/119226187-20d69b80-bb08-11eb-8f95-45777f4d7ec1.png)
![image](https://user-images.githubusercontent.com/9284124/119226191-29c76d00-bb08-11eb-8ef4-49e432603e30.png)

[benchy.gcode](https://zerobin.net/?4b00cc4696ff7273#g6cvVlHt9uQz1kJPSuY0KVSw74rRWdVf50AfpwRxef8=)
[benchy.csv](https://zerobin.net/?2f8001c2f4b96ba3#2sTqyaRFq0AdfYA9aIaUnq9DEMKnXBW4/ndHOokfMs8=)

**Comment by bmoniey** [comment]
Hello,

Excellent Thanks for reaching out and providing the sample gcode.

For some reason the layer count stated in the header is 121 layers, but the
actual layer count is 120.

I changed line 25 to
;LAYER_COUNT:120

bench.modified.gcode
<https://zerobin.net/?de0c305ff871baee#7hO/sZdZ8GJhLfvP8J9mQktAHUG/XYaS8FS2AobLIxI=>

Here is the result when I add some segments.

Let me know how the print turns out!

[image: image.png]

I will see what I can do to handle this and perhaps just use how many
layers are actually defined. Perhaps this came from your custom end gcode
footing, but it should be easy to handle.

Thanks,

Brian

**Comment by scmanjarrez** [comment]
Thank you very much for your prompt response, I have changed that layer count to 120 and now it's working fine.
I have tested again without start/end gcode, but still happening, maybe it's related with cura version (4.0.0)?
Anyway, just changing the layer count fixes it, so not a big deal.
I'll post the results!
Regards.

**Comment by bmoniey** [comment]
Wow so cool.

I just posted a slight update 1.1.1 which addresses the issue for your gcode sample.  I'm running cura 4.9 at the moment. I think the main reason to keep up with the versions is the printer configuration settings keep getting better. I can see the differences in the layer ringing is better at least for my Ender 3 printer. Visualization of the print is better too!

Did you try the filament welder?

https://grabcad.com/library/3dprint-filament-welder-1

Best wishes,

Brian
